# fly.toml file generated for coffee-bot-app on 2022-11-25T16:46:52+04:00

app = "coffee-bot-app"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = "8080"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  processes = ["app"]
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"
